# Generated by Django 2.2.6 on 2019-10-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=120)),
                ('Component', models.CharField(max_length=120)),
                ('Title', models.CharField(max_length=120)),
                ('Description', models.TextField()),
                ('CRID', models.CharField(max_length=20)),
                ('Prog_or_Comm', models.TextField()),
                ('Open', models.BooleanField(default=False)),
            ],
        ),
    ]
